[7zip]
paths = ["7zip/*"]
[acbuild]
paths = ["acbuild/*"]
[acl]
paths = ["acl/*"]
[ant]
paths = ["ant/*"]
[apr]
paths = ["apr/*"]
[apr-util]
paths = ["apr-util/*"]
[artifactory-pro]
paths = ["artifactory-pro/*"]
[aspcud]
paths = ["aspcud/*"]
[aspnet-sample]
paths = ["aspnet-sample/*"]
[attr]
paths = ["attr/*"]
[autoconf]
paths = ["autoconf/*"]
[autogen]
paths = ["autogen/*"]
[automake]
paths = ["automake/*"]
[aws-cli]
paths = ["aws-cli/*"]
[bash]
paths = ["bash/*"]
[bash-completion]
paths = ["bash-completion/*"]
[bash-static]
paths = ["bash-static/*"]
[bats]
paths = ["bats/*"]
[bc]
paths = ["bc/*"]
[bdwgc]
paths = ["bdwgc/*"]
[binutils]
paths = ["binutils/*"]
[bison]
paths = ["bison/*"]
[bison2]
paths = ["bison2/*"]
[boost]
paths = ["boost/*"]
[bundler]
paths = ["bundler/*"]
[busybox]
paths = ["busybox/*"]
[busybox-static]
paths = ["busybox-static/*"]
[bzip2]
paths = ["bzip2/*"]
[bzip2-musl]
paths = ["bzip2-musl/*"]
[cacerts]
paths = ["cacerts/*"]
[caddy]
paths = ["caddy/*"]
[cairo]
paths = ["cairo/*"]
[camlp4]
paths = ["camlp4/*"]
[cargo-nightly]
paths = ["cargo-nightly/*"]
[ccache]
paths = ["ccache/*"]
[check]
paths = ["check/*"]
[clens]
paths = ["clens/*"]
[clingo]
paths = ["clingo/*"]
[cmake]
paths = ["cmake/*"]
[composer]
paths = ["composer/*"]
[consul]
paths = ["consul/*"]
[coreutils]
paths = ["coreutils/*"]
[coreutils-static]
paths = ["coreutils-static/*"]
[cpanminus]
paths = ["cpanminus/*"]
[cpio]
paths = ["cpio/*"]
[cppunit]
paths = ["cppunit/*"]
[curator]
paths = ["curator/*"]
[curl]
paths = ["curl/*"]
[curl-static-musl]
paths = ["curl-static-musl/*"]
[cyrus-sasl]
paths = ["cyrus-sasl/*"]
[db]
paths = ["db/*"]
[dbus]
paths = ["dbus/*"]
[dd-agent]
paths = ["dd-agent/*"]
[dejagnu]
paths = ["dejagnu/*"]
[dep]
paths = ["dep/*"]
[devicemapper]
paths = ["devicemapper/*"]
[dex]
paths = ["dex/*"]
[diffutils]
paths = ["diffutils/*"]
[docker]
paths = ["docker/*"]
[docutils]
paths = ["docutils/*"]
[dosfstools]
paths = ["dosfstools/*"]
[dotnet-core]
paths = ["dotnet-core/*"]
[dotnet-core-lts]
paths = ["dotnet-core-lts/*"]
[dotnet-core-sdk]
paths = ["dotnet-core-sdk/*"]
[dotnet-core-sdk-lts]
paths = ["dotnet-core-sdk-lts/*"]
[doxygen]
paths = ["doxygen/*"]
[dpkg]
paths = ["dpkg/*"]
[drupal]
paths = ["drupal/*"]
[drush]
paths = ["drush/*"]
[e2fsprogs]
paths = ["e2fsprogs/*"]
[ed]
paths = ["ed/*"]
[elasticsearch]
paths = ["elasticsearch/*"]
[elfutils]
paths = ["elfutils/*"]
[elixir]
paths = ["elixir/*"]
[envdir]
paths = ["envdir/*"]
[erlang]
paths = ["erlang/*"]
[erlang16]
paths = ["erlang16/*"]
[erlang18]
paths = ["erlang18/*"]
[erlang19]
paths = ["erlang19/*"]
[etcd]
paths = ["etcd/*"]
[eudev]
paths = ["eudev/*"]
[expat]
paths = ["expat/*"]
[expect]
paths = ["expect/*"]
[ffmpeg]
paths = ["ffmpeg/*"]
[file]
paths = ["file/*"]
[findutils]
paths = ["findutils/*"]
[fish]
paths = ["fish/*"]
[flatbuffers]
paths = ["flatbuffers/*"]
[flex]
paths = ["flex/*"]
[fontconfig]
paths = ["fontconfig/*"]
[foulkon]
paths = ["foulkon/*"]
[freetype]
paths = ["freetype/*"]
[galera]
paths = ["galera/*"]
[gawk]
paths = ["gawk/*"]
[gcc]
paths = ["gcc/*"]
[gcc-libs]
paths = ["gcc-libs/*"]
[gdb]
paths = ["gdb/*"]
[gdbm]
paths = ["gdbm/*"]
[gecode]
paths = ["gecode/*"]
[geoip]
paths = ["geoip/*"]
[gettext]
paths = ["gettext/*"]
[giflib]
paths = ["giflib/*"]
[gifsicle]
paths = ["gifsicle/*"]
[git]
paths = ["git/*"]
[github_changelog_generator]
paths = ["github_changelog_generator/*"]
[glib]
paths = ["glib/*"]
[glibc]
paths = ["glibc/*"]
[gmp]
paths = ["gmp/*"]
[gnatsd]
paths = ["gnatsd/*"]
[gnupg]
paths = ["gnupg/*"]
[gnupg-static]
paths = ["gnupg-static/*"]
[go]
paths = ["go/*"]
[go14]
paths = ["go14/*"]
[go17]
paths = ["go17/*"]
[gox]
paths = ["gox/*"]
[gperf]
paths = ["gperf/*"]
[gpgme]
paths = ["gpgme/*"]
[gradle]
paths = ["gradle/*"]
[grafana]
paths = ["grafana/*"]
[graphviz]
paths = ["graphviz/*"]
[grep]
paths = ["grep/*"]
[groff]
paths = ["groff/*"]
[grub]
paths = ["grub/*"]
[gsl]
paths = ["gsl/*"]
[guile]
paths = ["guile/*"]
[gzip]
paths = ["gzip/*"]
[handlebars-cmd]
paths = ["handlebars-cmd/*"]
[haproxy]
paths = ["haproxy/*"]
[harfbuzz]
paths = ["harfbuzz/*"]
[htop]
paths = ["htop/*"]
[httpd]
paths = ["httpd/*"]
[iana-etc]
paths = ["iana-etc/*"]
[icu]
paths = ["icu/*"]
[icu52]
paths = ["icu52/*"]
[icu56]
paths = ["icu56/*"]
[imagemagick]
paths = ["imagemagick/*"]
[inetutils]
paths = ["inetutils/*"]
[intltool]
paths = ["intltool/*"]
[iproute2]
paths = ["iproute2/*"]
[iptables]
paths = ["iptables/*"]
[jbigkit]
paths = ["jbigkit/*"]
[jdk7]
paths = ["jdk7/*"]
[jdk8]
paths = ["jdk8/*"]
[jemalloc]
paths = ["jemalloc/*"]
[jenkins]
paths = ["jenkins/*"]
[jetty]
paths = ["jetty/*"]
[jfrog-cli]
paths = ["jfrog-cli/*"]
[jo]
paths = ["jo/*"]
[jq-static]
paths = ["jq-static/*"]
[jre7]
paths = ["jre7/*"]
[jre8]
paths = ["jre8/*"]
[jruby]
paths = ["jruby/*"]
[jruby1]
paths = ["jruby1/*"]
[kafka]
paths = ["kafka/*"]
[kibana]
paths = ["kibana/*"]
[kmod]
paths = ["kmod/*"]
[krb5]
paths = ["krb5/*"]
[lcms2]
paths = ["lcms2/*"]
[less]
paths = ["less/*"]
[leveldb]
paths = ["leveldb/*"]
[libaio]
paths = ["libaio/*"]
[libarchive]
paths = ["libarchive/*"]
[libarchive-musl]
paths = ["libarchive-musl/*"]
[libassuan]
paths = ["libassuan/*"]
[libatomic_ops]
paths = ["libatomic_ops/*"]
[libbsd]
paths = ["libbsd/*"]
[libcap]
paths = ["libcap/*"]
[libcap-ng]
paths = ["libcap-ng/*"]
[libcxx]
paths = ["libcxx/*"]
[libedit]
paths = ["libedit/*"]
[liberation-fonts-ttf]
paths = ["liberation-fonts-ttf/*"]
[libev]
paths = ["libev/*"]
[libevent]
paths = ["libevent/*"]
[libffi]
paths = ["libffi/*"]
[libgcrypt]
paths = ["libgcrypt/*"]
[libghthash]
paths = ["libghthash/*"]
[libgpg-error]
paths = ["libgpg-error/*"]
[libiconv]
paths = ["libiconv/*"]
[libidn]
paths = ["libidn/*"]
[libjpeg-turbo]
paths = ["libjpeg-turbo/*"]
[libksba]
paths = ["libksba/*"]
[libmpc]
paths = ["libmpc/*"]
[libossp-uuid]
paths = ["libossp-uuid/*"]
[libpcap]
paths = ["libpcap/*"]
[libpipeline]
paths = ["libpipeline/*"]
[libpng]
paths = ["libpng/*"]
[libressl]
paths = ["libressl/*"]
[libressl-musl]
paths = ["libressl-musl/*"]
[libscrypt]
paths = ["libscrypt/*"]
[libseccomp]
paths = ["libseccomp/*"]
[libsodium]
paths = ["libsodium/*"]
[libsodium-musl]
paths = ["libsodium-musl/*"]
[libtermkey]
paths = ["libtermkey/*"]
[libtiff]
paths = ["libtiff/*"]
[libtool]
paths = ["libtool/*"]
[libunistring]
paths = ["libunistring/*"]
[libunwind]
paths = ["libunwind/*"]
[libvterm]
paths = ["libvterm/*"]
[libwebp]
paths = ["libwebp/*"]
[libxml2]
paths = ["libxml2/*"]
[libxslt]
paths = ["libxslt/*"]
[libyajl2]
paths = ["libyajl2/*"]
[libyaml]
paths = ["libyaml/*"]
[linux]
paths = ["linux/*"]
[linux-headers]
paths = ["linux-headers/*"]
[linux-headers-musl]
paths = ["linux-headers-musl/*"]
[linux-pam]
paths = ["linux-pam/*"]
[llvm]
paths = ["llvm/*"]
[local-lib]
paths = ["local-lib/*"]
[logback]
paths = ["logback/*"]
[logstash]
paths = ["logstash/*"]
[logstash2]
paths = ["logstash2/*"]
[lsof]
paths = ["lsof/*"]
[lsyncd]
paths = ["lsyncd/*"]
[lttng-ust]
paths = ["lttng-ust/*"]
[lua]
paths = ["lua/*"]
[lynx]
paths = ["lynx/*"]
[lz4]
paths = ["lz4/*"]
[lzip]
paths = ["lzip/*"]
[lzo]
paths = ["lzo/*"]
[lzop]
paths = ["lzop/*"]
[m4]
paths = ["m4/*"]
[make]
paths = ["make/*"]
[man-db]
paths = ["man-db/*"]
[man-pages]
paths = ["man-pages/*"]
[mariadb]
paths = ["mariadb/*"]
[maven]
paths = ["maven/*"]
[mc]
paths = ["mc/*"]
[memcached]
paths = ["memcached/*"]
[mention-bot]
paths = ["mention-bot/*"]
[mercurial]
paths = ["mercurial/*"]
[mg]
paths = ["mg/*"]
[mongo-tools]
paths = ["mongo-tools/*"]
[mongodb]
paths = ["mongodb/*"]
[mpfr]
paths = ["mpfr/*"]
[mssql]
paths = ["mssql/*"]
[musl]
paths = ["musl/*"]
[mysql]
paths = ["mysql/*"]
[mysql-client]
paths = ["mysql-client/*"]
[nasm]
paths = ["nasm/*"]
[nats-streaming-server]
paths = ["nats-streaming-server/*"]
[nats-top]
paths = ["nats-top/*"]
[ncdu]
paths = ["ncdu/*"]
[ncurses]
paths = ["ncurses/*"]
[net-tools]
paths = ["net-tools/*"]
[netcat]
paths = ["netcat/*"]
[netcat-openbsd]
paths = ["netcat-openbsd/*"]
[nghttp2]
paths = ["nghttp2/*"]
[nginx]
paths = ["nginx/*"]
[ninja]
paths = ["ninja/*"]
[node]
paths = ["node/*"]
[node8]
paths = ["node8/*"]
[node_exporter]
paths = ["node_exporter/*"]
[npth]
paths = ["npth/*"]
[nspr]
paths = ["nspr/*"]
[nss]
paths = ["nss/*"]
[numactl]
paths = ["numactl/*"]
[ocaml]
paths = ["ocaml/*"]
[ocamlbuild]
paths = ["ocamlbuild/*"]
[omniORB]
paths = ["omniORB/*"]
[opam]
paths = ["opam/*"]
[openjpeg]
paths = ["openjpeg/*"]
[openldap]
paths = ["openldap/*"]
[openresty]
paths = ["openresty/*"]
[openssh]
paths = ["openssh/*"]
[openssl]
paths = ["openssl/*"]
[openssl-musl]
paths = ["openssl-musl/*"]
[openvpn]
paths = ["openvpn/*"]
[packer]
paths = ["packer/*"]
[pango]
paths = ["pango/*"]
[patch]
paths = ["patch/*"]
[patchelf]
paths = ["patchelf/*"]
[pax-utils]
paths = ["pax-utils/*"]
[pcre]
paths = ["pcre/*"]
[percona-xtrabackup]
paths = ["percona-xtrabackup/*"]
[perl]
paths = ["perl/*"]
[phantomjs]
paths = ["phantomjs/*"]
[php]
paths = ["php/*"]
[php5]
paths = ["php5/*"]
[pixman]
paths = ["pixman/*"]
[pkg-config]
paths = ["pkg-config/*"]
[polipo]
paths = ["polipo/*"]
[ponysay]
paths = ["ponysay/*"]
[popt]
paths = ["popt/*"]
[postgresql]
paths = ["postgresql/*"]
[postgresql93]
paths = ["postgresql93/*"]
[postgresql94]
paths = ["postgresql94/*"]
[postgresql95]
paths = ["postgresql95/*"]
[powershell]
paths = ["powershell/*"]
[procps-ng]
paths = ["procps-ng/*"]
[prometheus]
paths = ["prometheus/*"]
[protobuf]
paths = ["protobuf/*"]
[protobuf-c]
paths = ["protobuf-c/*"]
[protobuf-cpp]
paths = ["protobuf-cpp/*"]
[protobuf-rust]
paths = ["protobuf-rust/*"]
[psmisc]
paths = ["psmisc/*"]
[pv]
paths = ["pv/*"]
[python]
paths = ["python/*"]
[python2]
paths = ["python2/*"]
[qemu]
paths = ["qemu/*"]
[R]
paths = ["R/*"]
[rabbitmq]
paths = ["rabbitmq/*"]
[rabbitmqadmin]
paths = ["rabbitmqadmin/*"]
[raml2html]
paths = ["raml2html/*"]
[re2c]
paths = ["re2c/*"]
[readline]
paths = ["readline/*"]
[rebar3]
paths = ["rebar3/*"]
[redis]
paths = ["redis/*"]
[relx]
paths = ["relx/*"]
[repo]
paths = ["repo/*"]
[rethinkdb]
paths = ["rethinkdb/*"]
[rngd]
paths = ["rngd/*"]
[rpm]
paths = ["rpm/*"]
[rq]
paths = ["rq/*"]
[rsync]
paths = ["rsync/*"]
[ruby]
paths = ["ruby/*"]
[runit]
paths = ["runit/*"]
[rust]
paths = ["rust/*"]
[sassc]
paths = ["sassc/*"]
[scaffolding-base]
paths = ["scaffolding-base/*"]
[scaffolding-go]
paths = ["scaffolding-go/*"]
[scaffolding-go17]
paths = ["scaffolding-go17/*"]
[scaffolding-gradle]
paths = ["scaffolding-gradle/*"]
[scaffolding-node]
paths = ["scaffolding-node/*"]
[scaffolding-ruby]
paths = ["scaffolding-ruby/*"]
[scons]
paths = ["scons/*"]
[sed]
paths = ["sed/*"]
[sensu]
paths = ["sensu/*"]
[serf]
paths = ["serf/*"]
[shadow]
paths = ["shadow/*"]
[shield]
paths = ["shield/*"]
[shield-agent]
paths = ["shield-agent/*"]
[shield-proxy]
paths = ["shield-proxy/*"]
[snappy]
paths = ["snappy/*"]
[socat]
paths = ["socat/*"]
[spark]
paths = ["spark/*"]
[sqitch]
paths = ["sqitch/*"]
[sqlite]
paths = ["sqlite/*"]
[storm]
paths = ["storm/*"]
[strace]
paths = ["strace/*"]
[stringencoders]
paths = ["stringencoders/*"]
[subversion]
paths = ["subversion/*"]
[sudo]
paths = ["sudo/*"]
[swig]
paths = ["swig/*"]
[sysstat]
paths = ["sysstat/*"]
[systemd]
paths = ["systemd/*"]
[tar]
paths = ["tar/*"]
[tcl]
paths = ["tcl/*"]
[tcpdump]
paths = ["tcpdump/*"]
[telegraf]
paths = ["telegraf/*"]
[terraform]
paths = ["terraform/*"]
[texinfo]
paths = ["texinfo/*"]
[tmux]
paths = ["tmux/*"]
[tomcat-native]
paths = ["tomcat-native/*"]
[tomcat7]
paths = ["tomcat7/*"]
[tomcat8]
paths = ["tomcat8/*"]
[tor]
paths = ["tor/*"]
[traefik]
paths = ["traefik/*"]
[tree]
paths = ["tree/*"]
[ttyrec]
paths = ["ttyrec/*"]
[tzdata]
paths = ["tzdata/*"]
[unzip]
paths = ["unzip/*"]
[userspace-rcu]
paths = ["userspace-rcu/*"]
[util-linux]
paths = ["util-linux/*"]
[valgrind]
paths = ["valgrind/*"]
[varnish]
paths = ["varnish/*"]
[vault]
paths = ["vault/*"]
[vde2]
paths = ["vde2/*"]
[vim]
paths = ["vim/*"]
[virtualenv]
paths = ["virtualenv/*"]
[vmtouch]
paths = ["vmtouch/*"]
[wal-e]
paths = ["wal-e/*"]
[wget]
paths = ["wget/*"]
[wget-static]
paths = ["wget-static/*"]
[which]
paths = ["which/*"]
[wordpress]
paths = ["wordpress/*"]
[wordpress-proxy]
paths = ["wordpress-proxy/*"]
[wrk]
paths = ["wrk/*"]
[xz]
paths = ["xz/*"]
[xz-musl]
paths = ["xz-musl/*"]
[yarn]
paths = ["yarn/*"]
[yasm]
paths = ["yasm/*"]
[zeromq]
paths = ["zeromq/*"]
[zip]
paths = ["zip/*"]
[zlib]
paths = ["zlib/*"]
[zlib-musl]
paths = ["zlib-musl/*"]
[zookeeper]
paths = ["zookeeper/*"]
[zsh]
paths = ["zsh/*"]
[zstd]
paths = ["zstd/*"]
