[rabbitmq]

# Host on which to listen. An empty string means "listen on all interfaces."
listen_host=""

# Port to bind to.
listen_port=5672

# Virtual host to create when RabbitMQ creates a new database from scratch. The
# exchange amq.rabbitmq.log will exist in this virtual host.
default_vhost="/"

# User name to create when RabbitMQ creates a new database from scratch.
default_user="guest"

# Password for the default user.
default_pass="guest"

# Whether to enable the rabbitmq management plugin.
[rabbitmq.management]
enabled=false

# Clustering configuration

# Enable the cluster with `enabled = true`. Set a nice long random
# string for the cookie to have it get put into place. See the
# README.md for more information.
[rabbitmq.cluster]
enabled=false
erlang_cookie=false
