---
meta:
  delmo:
    machine_name: REDACTED
  dockerhub:
    email: REDACTED
    username: REDACTED
    password: REDACTED
  habitat:
    origin_key: REDACTED
    auth_token: REDACTED
    origin: core
  aws:
    docker-machine-bucket: docker-machine-bucket
    docker-machine-ami: ami-41e0b93b
    access_key_id: REDACTED
    secret_access_key: REDACTED
    region: us-east-1
  concourse:
    target: http://ip.of.concourse.web:8080
    team: REDACTED
    user: REDACTED
    password: REDACTED
  slack:
    webhook: REDACTED

groups:
- name: all-packages
  jobs: []
- name: docker-machine-setup
  jobs: [docker-machine-setup]

jobs:
- name: docker-machine-setup
  serial: true
  plan:
  - task: docker-machine-setup
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: habitat/docker-machine-setup }
      params:
        MACHINE_NAME: (( grab meta.delmo.machine_name ))
        AWS_DEFAULT_REGION: (( grab meta.aws.region ))
        AWS_ACCESS_KEY_ID: (( grab meta.aws.access_key_id ))
        AWS_SECRET_ACCESS_KEY: (( grab meta.aws.secret_access_key ))
        AWS_BUCKET: (( grab meta.aws.docker-machine-bucket ))
      run:
        path: /setup-aws

resources:
- name: habitat-plans-ci
  type: git
  source:
    uri: https://github.com/habitat-sh/core-plans.git
    paths: [ci/*]

- name: notify
  type: slack-notification
  source:
    url: (( grab meta.slack.webhook ))

resource_types:
- name: hab-pkg
  type: docker-image
  source:
    repository: cfcommunity/habitat-resource

- name: bldr-job
  type: docker-image
  source:
    repository: habitat/bldr-resource

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
